name: i3
version: 4.16.1
summary: i3 window manger.
description: A tiling window manager for X11.
  
adopt-info:i3

grade: stable
confinement: devmode

architectures:
  - build-on: amd64

apps:
    i3:
    command: bash
        slots: [mir, upower-observe]
        plugs:
        - home
        - x11
        - opengl
        - network
        - network-bind
        - unity7
        - pulseaudio
        - network-manager
        - udisks2
      
slots:
    -dbus:
        interface: dbus
        bus: session
        name: 
    -dbus:
        interface: dbus
        bus: session
        name: 
    -dbus:
        interface: dbus
        bus: session
        name: 
    -dbus:
        interface: dbus
        bus: session
        name: 
    -dbus:
        interface: dbus
        bus: session
        name: 
    -dbus:
        interface: dbus
        bus: session
        name: 
    -dbus:
        interface: dbus
        bus: session
        name: 
    -dbus:
        interface: dbus
        bus: session
        name: 
    -dbus:
        interface: dbus
        bus: session
        name: 
    -dbus:
        interface: dbus
        bus: session
        name: 
    -dbus:
        interface: dbus
        bus: session
        name: 
    -dbus:
        interface: dbus
        bus: session
        name: 
   -dbus:
        interface: dbus
        bus: session
        name: 
    -dbus:
        interface: dbus
        bus: session
        name: 

parts:
  i3:
  i3:
        stage-packages: [i3-workspace-wayland, i3, gdb, strace, vim, wayland-backend-x11, libxkbcommon-x11-0, libxkbcommon0, libx11-data, xkb-data, ltrace, kwrite, lxqt-workspace, konsole, kwin-wayland-backend-drm, libqt5sql5-sqlite]
        plugin: dump
        source: empty
        organize:
            usr/bin/Xwayland: usr/bin/Xwayland.orig
    patchy:
        after: [i3]
        plugin: dump
        source: xwayland
    source: http://http.us.debian.org/debian/i3_4.16.1-1_amd64.deb
    source-type: deb
   
    build-packages:
      - git
      - sed
      - libcairo2 
      - libev4  
      - libglib2.0-0 
      - libpango-1.0-0 
      - libpangocairo-1.0-0  
      - libpcre3     
      - libstartup-notification0 
      - libxcb-cursor0 
      - libxcb-icccm4       
      - libxcb-keysyms1      
      - libxcb-randr0      
      - libxcb-util1       
      - libxcb-xinerama0        
      - libxcb-xkb1
      - libxcb-xrm0 
      - libxcb1 
      - libxkbcommon-x11-0
      - libxkbcommon0       
      - libyajl2         
      - perl       
      - fonts-dejavu-core       
      - libanyevent-i3-perl         
      - libjson-xs-perl       
      - rxvt-unicode    
      - xfonts-base 
